// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: file_chunk.proto

package fileChunkProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashKey []byte `protobuf:"bytes,1,opt,name=hash_key,json=hashKey,proto3" json:"hash_key,omitempty"`
}

func (x *DownloadMessage) Reset() {
	*x = DownloadMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_chunk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMessage) ProtoMessage() {}

func (x *DownloadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_file_chunk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMessage.ProtoReflect.Descriptor instead.
func (*DownloadMessage) Descriptor() ([]byte, []int) {
	return file_file_chunk_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadMessage) GetHashKey() []byte {
	if x != nil {
		return x.HashKey
	}
	return nil
}

type UploadMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines int64 `protobuf:"varint,1,opt,name=lines,proto3" json:"lines,omitempty"`
}

func (x *UploadMessage) Reset() {
	*x = UploadMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_chunk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMessage) ProtoMessage() {}

func (x *UploadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_file_chunk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMessage.ProtoReflect.Descriptor instead.
func (*UploadMessage) Descriptor() ([]byte, []int) {
	return file_file_chunk_proto_rawDescGZIP(), []int{1}
}

func (x *UploadMessage) GetLines() int64 {
	if x != nil {
		return x.Lines
	}
	return 0
}

type FileMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashKey []byte `protobuf:"bytes,1,opt,name=hash_key,json=hashKey,proto3" json:"hash_key,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FileMessage) Reset() {
	*x = FileMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_file_chunk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMessage) ProtoMessage() {}

func (x *FileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_file_chunk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMessage.ProtoReflect.Descriptor instead.
func (*FileMessage) Descriptor() ([]byte, []int) {
	return file_file_chunk_proto_rawDescGZIP(), []int{2}
}

func (x *FileMessage) GetHashKey() []byte {
	if x != nil {
		return x.HashKey
	}
	return nil
}

func (x *FileMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_file_chunk_proto protoreflect.FileDescriptor

var file_file_chunk_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x2c, 0x0a, 0x0f, 0x44, 0x6f, 0x77, 0x6e,
	0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x68,
	0x61, 0x73, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x68,
	0x61, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x22, 0x25, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x3c, 0x0a,
	0x0b, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x68, 0x61, 0x73, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x68, 0x61, 0x73, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x78, 0x0a, 0x04, 0x46,
	0x69, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x15, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x11, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x36, 0x0a,
	0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x11, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x13, 0x2e, 0x66, 0x69, 0x6c,
	0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22,
	0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x11, 0x5a, 0x0f, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_file_chunk_proto_rawDescOnce sync.Once
	file_file_chunk_proto_rawDescData = file_file_chunk_proto_rawDesc
)

func file_file_chunk_proto_rawDescGZIP() []byte {
	file_file_chunk_proto_rawDescOnce.Do(func() {
		file_file_chunk_proto_rawDescData = protoimpl.X.CompressGZIP(file_file_chunk_proto_rawDescData)
	})
	return file_file_chunk_proto_rawDescData
}

var file_file_chunk_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_file_chunk_proto_goTypes = []interface{}{
	(*DownloadMessage)(nil), // 0: file.DownloadMessage
	(*UploadMessage)(nil),   // 1: file.UploadMessage
	(*FileMessage)(nil),     // 2: file.FileMessage
}
var file_file_chunk_proto_depIdxs = []int32{
	0, // 0: file.File.Download:input_type -> file.DownloadMessage
	2, // 1: file.File.Upload:input_type -> file.FileMessage
	2, // 2: file.File.Download:output_type -> file.FileMessage
	1, // 3: file.File.Upload:output_type -> file.UploadMessage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_file_chunk_proto_init() }
func file_file_chunk_proto_init() {
	if File_file_chunk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_file_chunk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_chunk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_file_chunk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_file_chunk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_file_chunk_proto_goTypes,
		DependencyIndexes: file_file_chunk_proto_depIdxs,
		MessageInfos:      file_file_chunk_proto_msgTypes,
	}.Build()
	File_file_chunk_proto = out.File
	file_file_chunk_proto_rawDesc = nil
	file_file_chunk_proto_goTypes = nil
	file_file_chunk_proto_depIdxs = nil
}
